export const FETCH_URL = 'FETCH_URL';
export const LOADING_FETCH_URL = 'LOADING_FETCH_URL';
export const UPDATE_FETCH_URL = 'UPDATE_FETCH_URL';
export const FAIL_FETCH_URL = 'FAIL_FETCH_URL';

export const ADD_LINK = 'ADD_LINK';
export const LOADING_ADD_LINK = 'LOADING_ADD_LINK';
export const UPDATE_ADD_LINK = 'UPDATE_ADD_LINK';
export const FAIL_ADD_LINK = 'FAIL_ADD_LINK';

export const ADD_SOURCE = 'ADD_SOURCE';
export const LOADING_ADD_SOURCE = 'LOADING_ADD_SOURCE';
export const UPDATE_ADD_SOURCE = 'UPDATE_ADD_SOURCE';
export const FAIL_ADD_SOURCE = 'FAIL_ADD_SOURCE';

export const ADD_SENTIMENT = 'ADD_SOURCE';
export const LOADING_ADD_SENTIMENT = 'LOADING_ADD_SENTIMENT';
export const UPDATE_ADD_SENTIMENT = 'UPDATE_ADD_SENTIMENT';
export const FAIL_ADD_SENTIMENT = 'FAIL_ADD_SENTIMENT';

export const ADD_INTEREST = 'ADD_INTEREST';
export const LOADING_ADD_INTEREST = 'LOADING_ADD_INTEREST';
export const UPDATE_ADD_INTEREST = 'UPDATE_ADD_INTEREST';
export const FAIL_ADD_INTEREST = 'FAIL_ADD_INTEREST';
